instance_type    = "t3.micro"
project          = "shopping"
env              = "developement"
hosted_zone_name = "basilsdomain.online"
hosted_zone_id   = "Z006794722XVZY9MQ08TI"
hostname         = "developement"
