---
name: "Development Infra"

on:
  repository_dispatch:
    types: [ deployment-in-dev-env ]

  push:
    branches:
      - developement
      - 'feature/**'
        
jobs:
    
  build:
    runs-on: ubuntu-latest

    steps:

      - name: "Repository Checkout"
        uses: actions/checkout@v3


      - name: "Terraform Installation"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2
     
      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.DEV_S3 }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=eu-north-1" \
            -backend-config="access_key=${{ secrets.DEV_ACCESS }}" \
            -backend-config="secret_key=${{ secrets.DEV_SECRET }}" \

      - name: Terraform fmt
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file=dev.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET }}
          AWS_REGION: "eu-north-1"
                
      - name: Terraform apply
        run: |
           terraform apply \
              -auto-approve \
              -var-file=dev.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET }}
          AWS_REGION: "eu-north-1"
