---
name: "Poduction Infra"

on:
  repository_dispatch:
    types: [ deployment-in-prod-env ]

  push:
    branches:
      - production

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_ACCESS}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_SECRET}}
      AWS_DEFAULT_REGION: ${{ secrets.PROD_REGION }}

    steps:
  
      - name: "Date"
        run: date
        
      - name: "OS"
        run : cat /etc/issue

      - name: "terraform Installation"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: "Initialize terraform"
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.PROD_S3 }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${{ secrets.PROD_REGION }}" \
            -backend-config="access=${{ secrets.PROD_ACCESS }}" \
            -backend-config="secret=${{ secrets.PROD_SECRET }}" \

      - name: "terraform fmt"
        run: terraform fmt

      - name: "terraform validate"
        run: terraform validate

      - name: "terraform plan"
        run: terraform plan -var-file=prod.tfvars

      - name: "terraform apply"
        run: | 
          terraform apply \
            -var-file=prod.tfvars \
            -auto-approve
